"""Project configuration defaults."""

DEFAULT_ENGINE = "stock"
DEFAULT_MARKET = "shares"
DEFAULT_BOARD = "TQBR"
DEFAULT_START_DATE = "2020-01-01"
DEFAULT_INTERVAL = 24
DEFAULT_COMMISSION_BPS = 5.0
DEFAULT_SLIPPAGE_BPS = 10.0
TRADABLE_AVG_VALUE_THRESHOLD = 10_000_000
MIN_OBSERVATIONS = 100
